export const movieMood = {
  Action: "😄 Exciting",
  Adventure: "😲 Thrilling",
  Animation: "😀 Playful",
  Comedy: "😂 Funny",
  Crime: "😬 Suspense",
  Documentary: "🧐 Insight",
  Drama: "😳 Drama",
  Family: "🥰 Heartwarming",
  Fantasy: "🤩 Imagination",
  History: "🤔 Reflection",
  Horror: "😱 Scary",
  Music: "🎶 Melodic",
  Mystery: "🕵️‍♂️ Mysterious",
  Romance: "😍 Romantic",
  "Science Fiction": "🚀 Sci-Fi",
  "TV Movie": "📺 Entertainment",
  Thriller: "😬 Tension",
  War: "😡 Intense",
  Western: "🤠 Classic",
};
