export const movieMood = {
  Action: "😄 Excitement",
  Adventure: "😲 Thrill",
  Animation: "😀 Playfulness",
  Comedy: "😂 Humor",
  Crime: "😬 Suspense",
  Documentary: "🧐 Insight",
  Drama: "😳 Intensity",
  Family: "🥰 Warmth",
  Fantasy: "🤩 Imagination",
  History: "🤔 Reflection",
  Horror: "😱 Fear",
  Music: "🎶 Harmony",
  Mystery: "🕵️‍♂️ Intrigue",
  Romance: "😍 Affection",
  "Science Fiction": "🚀 Wonder",
  "TV Movie": "📺 Entertainment",
  Thriller: "😬 Tension",
  War: "😡 Conflict",
  Western: "🤠 Frontier",
};
